'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const publicCommit='65d7b9b47f2558f7578b1471d2a0f089d717d05d';
const sourceBase=`https://github.com/DigitalArtDeco/DAD-FieldWorks-Showcase/blob/${publicCommit}/`;
const assets={
 'hy-longitudinal':{file:'hy-longitudinal.png',preview:'hy-longitudinal-preview.png',title:'Longitudinal field slice',alt:'Saved H y component in a longitudinal slice of the Uniform Shielded TEM Reference Line with transparent geometry.',context:'Hᵧ in A/m. Normal Y, index 10. Step 4096 at 1.023875 ns. The colour scale and original image pixels are unchanged.',date:'Image selection: 13 Sep 2026',manifest:'evidence/manifest-application-2026-09-12.json'},
 'hy-transverse':{file:'hy-transverse.png',preview:'hy-transverse-preview.png',title:'Transverse field slice',alt:'Saved H y cross section inside the transparent geometry of the shielded reference line.',context:'Hᵧ in A/m. Normal X, index 21. The same saved step 4096 as the longitudinal view. This is neither a different frequency nor another time step.',date:'Image selection: 13 Sep 2026',manifest:'evidence/manifest-application-2026-09-12.json'},
 'hy-contours':{file:'hy-contours.png',preview:'hy-contours-preview.png',title:'Field and geometry contours',alt:'H y cross section with conductor geometry contours and the complete colour scale.',context:'Hᵧ in A/m. Normal X, index 21. Contours locate the field within the authoring geometry. They do not represent compiled solver cells.',date:'Image selection: 13 Sep 2026',manifest:'evidence/manifest-application-2026-09-12.json'},
 smith:{file:'smith-chart.png',title:'Reflection and impedance',alt:'Original DAD FieldWorks Smith chart for S(2,2) of the Uniform Shielded TEM Reference Line at 5.500 GHz with a 50 ohm reference.',context:'Original Smith chart: S(2,2), 5.500 GHz, 50 Ω. The marker describes the reflection result, not the saved time domain field slices. The outer scales are graphical aids.',date:'Image selection: 13 Sep 2026',manifest:'evidence/manifest-application-2026-09-12.json'},
 cartesian:{file:'cartesian.png',title:'Via Transition S parameters',alt:'DAD FieldWorks Via Transition with four S parameter traces in linear magnitude and a marker at 1.700 GHz.',context:'Via Transition. Linear magnitude, not dB. The marker is at 1.700 GHz. Straight segments connect available samples. This is a different test case from the shielded TEM reference line.',date:'Earlier image selection: 09 Sep 2026',manifest:'evidence/manifest-application-2026-09-09.json'},
 model:{file:'reference-model.png',title:'The reference model',alt:'Authoring geometry of the shielded TEM reference line with port labels p1 and p2.',context:'Original cropped view of the Uniform Shielded TEM Reference Line and its ports. This view alone does not establish general CAD capabilities or actual solver cell occupancy.',date:'Image selection: 13 Sep 2026',manifest:'evidence/manifest-application-2026-09-12.json'},
 sketcher:{file:'sketcher.png',title:'Planar geometry in the RF Sketcher',alt:'Original RF Sketcher view of the Tuto project with planar contours.',context:'Separate example: Tuto. This earlier screenshot reports no results and unevaluated constraints. It is not evidence of a successful simulation or of the latest parametric editing repairs.',date:'Earlier image selection: 09 Sep 2026',manifest:'evidence/manifest-application-2026-09-09.json'},
 pulse:{file:'pulse-reference.png',title:'Pulse against a numerical reference',alt:'Original diagnostic comparing the 3D pulse with a separately implemented scalar reference, including electric and magnetic error norms.',context:'Internal numerical check of a homogeneous, lossless TEM line with ideal conducting boundaries. Electric and magnetic errors retain their original axes and units. This is not an experimental measurement.',date:'Published: 10 Sep 2026',manifest:'evidence/manifest-solver-development.json'},
 return:{file:'returning-wave.png',title:'Returning wave at an active source',alt:'Original comparison of incident, returning and jointly calculated waves in both directions.',context:'A, R and AR are separate calculations within the same TEM source test family. The plots include AR − A − R. The combined response was actually calculated. This is not a general multiport qualification.',date:'Published: 10 Sep 2026',manifest:'evidence/manifest-solver-development.json'}
};
const configs={
 field:{project:'Uniform Shielded TEM Reference Line',title:'See the field in its geometry.',desc:'Where is the field, and how does it relate to the structure? Saved native field components reveal the spatial context of a computed result.',facts:[['Component','Hᵧ · A/m'],['Saved step','4096'],['Time','1.023875 ns'],['Model','Shielded TEM line']],note:'Three views of the same time step. These field images are not an animation and are not fields at the selected Smith frequency.',caption:'Saved field state · Original image excerpt',choices:[['hy-longitudinal','Longitudinal'],['hy-transverse','Transverse'],['hy-contours','Contours'],['compare','Compare']],initial:'hy-longitudinal'},
 smith:{project:'Uniform Shielded TEM Reference Line',title:'Put reflection in context.',desc:'The Smith chart relates complex reflection to input impedance. This original view shows S(2,2) together with its numerical readouts.',facts:[['S parameter','S(2,2)'],['Marker','5.500 GHz'],['Reference','50 Ω'],['View','Smith + wavelength scales']],note:'The outer scales are graphical aids for a lossless line convention. They do not establish deembedding or a separate physical length calculation.',caption:'Shielded reference line · Actual solver results',choices:[],initial:'smith'},
 cartesian:{project:'Via Transition',title:'Inspect reflection and transmission.',desc:'Four complex S parameters are shown as linear magnitudes. Compare reflection and transmission at the available frequency samples.',facts:[['Traces','S11, S12, S21, S22'],['Marker','1.700 GHz'],['Quantity','Linear magnitude'],['Test case','Via Transition']],note:'A separate test case. Straight segments connect available samples; they do not imply a densely sampled sweep or computed intermediate values.',caption:'Via Transition · A separate case from the Smith chart',choices:[],initial:'cartesian'},
 model:{project:'Uniform Shielded TEM Reference Line',title:'From geometry to a numerical model.',desc:'Conductors, layer stackup and ports define the starting point. DAD FieldWorks has its own geometry workflow for supported PCB and RF structures.',facts:[['View','Authoring geometry'],['Port labels','p1, p2'],['Application','Windows'],['Status','Development preview']],note:'Authoring geometry and compiled solver geometry are separate data layers. This capture shows the model, not its numerical cell occupancy.',caption:'Reference model · Original image excerpt',choices:[['model','Reference model'],['sketcher','RF Sketcher']],initial:'model'}
};
let currentTab='field',currentAsset='hy-longitudinal',currentEvidence='pulse',lastFocus=null;
let registryPromise=fetch('evidence/asset-register.json').then(r=>{if(!r.ok)throw Error('Source register unavailable');return r.json()});
let spacingPromise=fetch('evidence/analytical-spacing.json').then(r=>{if(!r.ok)throw Error('Reference records unavailable');return r.json()});
registryPromise.catch(()=>{});spacingPromise.catch(()=>{});
function escapeHTML(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function facts(rows){$('#result-facts').innerHTML=rows.map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('');}
function renderResult(tab){currentTab=tab;const c=configs[tab];$$('[data-tab]').forEach(b=>{const on=b.dataset.tab===tab;b.setAttribute('aria-selected',on);b.tabIndex=on?0:-1;});$('#result-panel').setAttribute('aria-labelledby','tab-'+tab);$('#project-name').textContent=c.project;$('#result-title').textContent=c.title;$('#result-description').textContent=c.desc;$('#result-note').textContent=c.note;$('#image-caption').textContent=c.caption;facts(c.facts);$('#view-controls').innerHTML=c.choices.map(([id,label])=>`<button data-view="${id}" aria-pressed="false">${label}</button>`).join('');$('#view-controls').hidden=!c.choices.length;renderView(c.initial);}
function renderView(id){currentAsset=id;$$('[data-view]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.view===id));const visual=$('#result-visual');visual.classList.toggle('light',!['hy-longitudinal','hy-transverse','hy-contours','compare'].includes(id));
 if(id==='compare'){visual.innerHTML=`<div class="compare-pair"><figure><button data-open-image="hy-transverse" aria-label="Enlarge the cross section in transparent geometry"><img src="assets/hy-transverse-preview.png" alt="Cross section inside transparent geometry"></button><figcaption>Spatial context <span>↗</span></figcaption></figure><figure><button data-open-image="hy-contours" aria-label="Enlarge the cross section with geometry contours"><img src="assets/hy-contours-preview.png" alt="The same slice with geometry contours from a different camera perspective"></button><figcaption>Geometry contours <span>↗</span></figcaption></figure></div>`;$('#image-caption').textContent='Same step and slice · Different camera perspectives';$('#result-note').textContent='Both original views show Hᵧ at step 4096, normal X, index 21, with the same colour scale. The camera perspectives differ. Open either image to inspect it in detail.';
 }else{const a=assets[id];visual.innerHTML=`<button data-open-image="${id}" aria-label="Enlarge ${escapeHTML(a.title)}"><img src="assets/${a.preview||a.file}" alt="${escapeHTML(a.alt)}"></button>`;$('#image-caption').textContent=configs[currentTab].caption;$('#result-note').textContent=configs[currentTab].note;}
 if(currentTab==='field'){facts([...configs.field.facts.slice(0,3),['Slice',id==='hy-longitudinal'?'Normal Y · Index 10':'Normal X · Index 21']]);}
 if(currentTab==='model'){const sketch=id==='sketcher';$('#project-name').textContent=sketch?'Tuto · Separate geometry example':configs.model.project;$('#result-title').textContent=sketch?'Author planar contours.':configs.model.title;$('#result-description').textContent=sketch?'The native RF Sketcher supports planar geometry construction. This earlier Tuto capture illustrates the editor; it does not show the newer parametric construction history.':configs.model.desc;$('#result-note').textContent=sketch?assets.sketcher.context:configs.model.note;$('#image-caption').textContent=sketch?'Tuto · Geometry example without a simulation result':configs.model.caption;facts(sketch?[['Project','Tuto'],['View','Planar contours'],['Results','None'],['Constraints','Not evaluated']]:configs.model.facts);}
}
function openModal(dialog){lastFocus=document.activeElement;dialog.showModal();document.body.style.overflow='hidden';}
function closeModal(dialog){dialog.close();}
// Escape closes the dialog even when a search field would otherwise consume it.
document.addEventListener('keydown',e=>{if(e.key==='Escape'){const active=$('dialog[open]');if(active){e.preventDefault();closeModal(active);}}},true);
$$('dialog').forEach(d=>{d.addEventListener('close',()=>{document.body.style.overflow='';if(lastFocus?.isConnected)lastFocus.focus();});d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal(d);}});});
function openImage(id){const a=assets[id];if(!a)return;$('#image-dialog-title').textContent=a.title;$('#dialog-image').src='assets/'+a.file;$('#dialog-image').alt=a.alt;$('#dialog-image-caption').textContent=a.context;$('#image-download').href='assets/'+a.file;$('#image-download').download=a.file;$('#zoom').value=100;updateZoom();openModal($('#image-dialog'));}
function updateZoom(){$('#dialog-image').style.width=$('#zoom').value+'%';$('#zoom-value').textContent=$('#zoom').value+' %';}
function openInfo(title,body,label='SOURCE & CONTEXT'){$('#info-title').textContent=title;$('#info-label').textContent=label;$('#info-body').innerHTML=body;openModal($('#info-dialog'));}
async function showSource(id){const a=assets[id];openInfo(a.title,`<p>${a.context}</p><p>Loading provenance …</p>`);try{const reg=await registryPromise;const entry=reg.assets.find(x=>x.file==='assets/'+a.file);$('#info-body').innerHTML=`<span class="tag">${a.date}</span><p>${a.context}</p><div class="source-data"><dl><dt>Origin</dt><dd>DigitalArtDeco Labs public showcase repository</dd><dt>File</dt><dd>${a.file}</dd><dt>Processing</dt><dd>Existing public PNG copied without modification.</dd><dt>SHA256</dt><dd><code>${entry.sha256}</code></dd><dt>Source revision</dt><dd><code>${publicCommit}</code><br>Website commit, not an application build identity.</dd></dl></div><div class="verify-row"><button class="button secondary" id="verify-file" data-verify="${id}">Verify this file <span>↗</span></button><span class="verify-status" id="verify-status" role="status"></span></div><h4>What this establishes</h4><p>A matching hash confirms that this file is identical to the recorded source asset. It does not verify physical accuracy or software release status. These images are not attributed to the latest product commit.</p><p><a href="${entry.source_url}" target="_blank" rel="noopener noreferrer">Original at the fixed source revision ↗</a><br><a href="${a.manifest}" target="_blank" rel="noopener noreferrer">Original image manifest ↗</a><br><a href="assets/${a.file}" download="${a.file}">Download the original file ↓</a></p>`;}catch(e){$('#info-body').innerHTML=`<p>The source register is currently unavailable. The original image remains available.</p><a href="${a.manifest}">Open image manifest</a>`;}}
async function verifyFile(id){const button=$('#verify-file'),status=$('#verify-status');button.disabled=true;status.textContent='Reading and hashing the file …';try{const reg=await registryPromise,entry=reg.assets.find(x=>x.file==='assets/'+assets[id].file);const r=await fetch(entry.file,{cache:'no-store'});if(!r.ok)throw Error('File unavailable');const buf=await r.arrayBuffer();const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',buf))].map(x=>x.toString(16).padStart(2,'0')).join('');status.textContent=hash===entry.sha256?'✓ Identical to the recorded original':'Mismatch: this file does not match the recorded hash.';}catch(e){status.textContent='Verification unavailable. Please check the manifest or try again.';}button.disabled=false;}
const evidenceContent={pulse:{title:'Does the pulse follow its numerical reference?',desc:'The 3D solver and a separately implemented scalar reference are compared under the same defined conditions. The lower panels retain the electric and magnetic error norms.',meta:'TEM SOURCE CHECK',foot:'A specific internal numerical check. Not measurement data.'},return:{title:'Can a returning wave cross the active source?',desc:'Incident, returning and combined excitations are calculated separately. The difference AR − A − R reveals remaining superposition errors in both directions.',meta:'SAME TEM TEST FAMILY',foot:'A bounded source check. Not general multiport qualification.'}};
async function renderEvidence(id){currentEvidence=id;$$('[data-evidence]').forEach(b=>{const active=b.dataset.evidence===id;b.setAttribute('aria-selected',active);b.tabIndex=active?0:-1;});$('#evidence-panel').setAttribute('aria-labelledby','ev-'+id);if(id==='spacing'){await renderSpacing();return;}if(id==='development'){renderDevelopment();return;}const c=evidenceContent[id],a=assets[id];$('#evidence-panel').innerHTML=`<div class="evidence-detail-head"><span class="tag">Internal numerical evidence</span><span>${c.meta}</span></div><h3>${c.title}</h3><p class="ev-desc">${c.desc}</p><button class="evidence-figure" data-open-image="${id}" aria-label="Enlarge ${a.title}"><img src="assets/${a.file}" alt="${a.alt}" loading="lazy"></button><div class="evidence-actions"><span>${c.foot}</span><button class="text-button" data-source="${id}">Original &amp; evidence ↗</button></div>`;}
function number(x,d=3){return x.toLocaleString('en-GB',{minimumFractionDigits:d,maximumFractionDigits:d});}
async function renderSpacing(){$('#evidence-panel').innerHTML='<p class="ev-desc">Loading analytical reference records …</p>';try{const data=await spacingPromise;if(currentEvidence!=='spacing')return;const rows=data.record.rows;$('#evidence-panel').innerHTML=`<div class="evidence-detail-head"><span class="tag">Analytical reference</span><span>SI KERNEL v0.3</span></div><h3>What changes with trace spacing?</h3><p class="ev-desc">Three saved analytical reference points for a differential pair. Select a spacing to inspect its recorded impedances.</p><div class="record-inputs"><span>εᵣ = 4.1</span><span>Height = 0.5 mm</span><span>Width = 0.5 mm</span><span>Thickness = 0 mm</span></div><span class="label">SELECT A RECORDED SPACING</span><div class="spacing-selector">${rows.map((r,i)=>`<button data-spacing="${i}" aria-pressed="${i===1}">${number(r.spacingMm,2)} mm</button>`).join('')}</div><div class="spacing-result" aria-live="polite"><div><small>Differential impedance</small><strong id="zdiff"></strong></div><div><small>Common mode impedance</small><strong id="zcommon"></strong></div></div><table class="data-table"><caption class="label">AVAILABLE REFERENCE POINTS</caption><thead><tr><th scope="col">Spacing</th><th scope="col">Z diff</th><th scope="col">Z common</th><th scope="col">K</th></tr></thead><tbody>${rows.map((r,i)=>`<tr data-data-row="${i}"><td>${number(r.spacingMm,2)} mm</td><td>${number(r.zdiffOhm)} Ω</td><td>${number(r.zcommonOhm)} Ω</td><td>${number(r.K,4)}</td></tr>`).join('')}</tbody></table><div class="evidence-actions"><span>Analytical model. Not a 3D field simulation or measurement.<br>Displayed values are rounded. Full precision is in the source file.</span><button class="text-button" data-dialog="analytic">Data &amp; context ↗</button></div>`;updateSpacing(1);}catch(e){if(currentEvidence==='spacing')$('#evidence-panel').innerHTML='<p>Reference data are currently unavailable. <a href="evidence/analytical-spacing.json">Open the source file</a></p>';}}
async function updateSpacing(i){const data=await spacingPromise;if(currentEvidence!=='spacing'||!$('#zdiff'))return;const r=data.record.rows[i];$('#zdiff').innerHTML=number(r.zdiffOhm)+' <span>Ω</span>';$('#zcommon').innerHTML=number(r.zcommonOhm)+' <span>Ω</span>';$$('[data-spacing]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.spacing)===i));$$('[data-data-row]').forEach(tr=>tr.classList.toggle('current',Number(tr.dataset.dataRow)===i));}
const scopeRows=[
 ['Geometry & stackup','Retained parametric RF sketches, a 2 to 16 conductor layer editor and interactive through, blind and buried vias.','Supported topology and editing contracts. Not a general mechanical CAD kernel.'],
 ['Simulation setup','Local terminal contacts, source and load settings, and explicit setup recommendations for supported open microstrip geometry.','The documented straight line is a bounded test case. A planned width transition is not yet a qualified RF result.'],
 ['Results & persistence','Complex S matrices, Cartesian and Smith views, saved native fields, project reopening and bounded Touchstone export.','Physical input changes retain stale result detection and export blocking. Invalid results are not filled in.'],
 ['Material models','Source bound material records and explicit passive conductivity and multiple pole Debye models.','Published observations are distinct from executable models. No automatic fit or general material accuracy claim.']
];
function scopeTable(){return `<div class="scope-rows">${scopeRows.map(([title,body,limit])=>`<details><summary>${title}<span>+</span></summary><p>${body}</p><small>${limit}</small></details>`).join('')}</div>`;}
function renderDevelopment(){$('#evidence-panel').innerHTML=`<div class="evidence-detail-head"><span class="tag">Repository review</span><span>15 SEP 2026</span></div><h3>The current product scope.</h3><p class="ev-desc">The latest source checkpoint integrates terminal ports, parametric editing, setup and usability repairs. Explore the implemented scope below.</p>${scopeTable()}<div class="reported-result"><strong>A documented open microstrip example</strong><p>Two independent excitations produce 12 valid complex S entries across 0.9, 1.7 and 2.8 GHz, with native fields, saved views and a checked Touchstone export.</p><small>Reported in the existing internal calculation and reconstruction records. The latest integration did not rerun this calculation.</small></div><div class="evidence-actions"><span>Review of code and existing records.<br>No new solver execution or external validation.</span><button class="text-button" data-dialog="development">Review &amp; remaining limits ↗</button></div>`;}
const registerItems=[
 {title:'Current development scope',text:'A read only review of the product branch on 15 Sep 2026. Separates implemented features, previously reported numerical cases and unresolved qualification. The underlying source and execution records are private and are not reproduced here.',local:'evidence/development-scope.md'},
 {title:'Field views and reference model',text:'Three Hᵧ views of the same saved step. Selected on 13 Sep 2026; the original desktop clock shows 12 Sep. No independently supplied capture timestamp or executable build identity.',path:'assets/images/dad-fieldworks/application-2026-09-12/manifest.json',local:'evidence/manifest-application-2026-09-12.json'},
 {title:'Smith chart and reflection',text:'Shielded TEM reference line. S(2,2), 5.500 GHz and 50 Ω. Original wavelength scales. No external measurement correlation.',path:'docs/company_screenshot_provenance.md',local:'evidence/company_screenshot_provenance.md'},
 {title:'Cartesian S parameters and RF Sketcher',text:'Via Transition with linear magnitude and a 1.700 GHz marker. Separately, Tuto geometry without simulation results. Earlier image selection from 09 Sep 2026.',path:'assets/images/dad-fieldworks/application-2026-09-09/manifest.json',local:'evidence/manifest-application-2026-09-09.json'},
 {title:'Numerical TEM source checks',text:'Original pulse comparison and returning wave checks. Two figures from one source test family, published on 10 Sep 2026. Not independent experimental studies.',path:'assets/images/solver-development/manifest.json',local:'evidence/manifest-solver-development.json'},
 {title:'Analytical reference records',text:'Historical SI Kernel v0.3. Three original spacing and impedance records from the public dataset. These are not full wave simulation results. The old roadmap is not used as a description of current capabilities.',path:'data/dad_signal_integrity_v0_3_examples.json',local:'evidence/analytical-spacing.json'},
 {title:'Earlier public product documentation',text:'Public scope updated 13 Sep 2026, with an implementation review dated 06 Sep. Preserved as historical context for the images. See the newer development scope for material, terminal and authoring updates.',path:'docs/current_public_status.md',local:'evidence/current_public_status.md'},
 {title:'Image identity in this showcase',text:'All 14 copied image assets retain their original bytes. The asset register links each copy to the public website commit. Hashes establish file identity, not physical accuracy.',local:'evidence/asset-register.json'}
];
function registerHTML(query=''){const q=query.toLocaleLowerCase('en');const matches=registerItems.filter(r=>(r.title+' '+r.text).toLocaleLowerCase('en').includes(q));return matches.length?matches.map(r=>`<div class="register-item"><strong>${r.title}</strong><p>${r.text}</p><a href="${r.local}" target="_blank" rel="noopener noreferrer">Read the record ↗</a>${r.path?`<a href="${sourceBase+r.path}" target="_blank" rel="noopener noreferrer">Fixed public source revision ↗</a>`:''}</div>`).join(''):'<p class="no-results" role="status">No matching record. Try “TEM”, “Smith” or “geometry”.</p>';}
function showRegister(){openInfo('The source register',`<p>The original images and public diagnostics come from the public showcase at <code>${publicCommit}</code>. This is a website revision, not a solver build. The current development summary is a separate review of newer private product records.</p><label class="label" for="source-search">SEARCH THE SOURCES</label><input class="source-search" id="source-search" type="search" placeholder="For example, Smith, TEM or geometry"><div class="register-list" id="register-list">${registerHTML()}</div>`,'ORIGINAL ASSETS & DOCUMENTATION');}
function showScope(){openInfo('Implemented scope and its limits',`<span class="tag">Development preview · reviewed 15 Sep 2026</span><p>DAD FieldWorks brings supported PCB geometry, stackup, materials, ports and frequencies into a native workflow with real solver jobs, complex S matrices and saved fields. The current branch includes newer capabilities than the earlier public image documentation.</p>${scopeTable()}<h4>Evidence keeps its original scope</h4><p>The documented open microstrip case produced 12 valid complex S entries, saved fields and a real Touchstone export. A separate historical eight port reference produced 192 valid complex entries. These are bounded internal results from different cases, not a general accuracy benchmark. The latest integration checkpoint started no new field or mode calculation.</p><h4>What remains open</h4><p>Full external mouse and desktop acceptance of the latest combined workflow remains open. General patch qualification, smooth curved copper surface losses, external validation and production release are not established. Local terminals are not calibrated open wave ports, and no deembedding is claimed.</p><h4>Original results, without invented samples</h4><p>The images show actual saved views. The public source package does not supply the full raw matrices behind these captures. This website therefore does not reconstruct additional S values, frequency samples or field states. The older lossless TEM images are not evidence of newer lossy material support.</p><p><a href="evidence/development-scope.md" target="_blank" rel="noopener noreferrer">Read the current development summary ↗</a><br><a href="${sourceBase}docs/claim_boundaries.md" target="_blank" rel="noopener noreferrer">Original public image boundaries ↗</a></p>`,'CAPABILITIES & LIMITS');}
function showDevelopment(){openInfo('Repository review and current development',`<span class="tag">Source and records reviewed · 15 Sep 2026</span><p>The reviewed feature branch includes the 15 September integration of local terminal ports, retained parametric constructions, simulation setup, application branding and input repairs. Its Project Master and supporting reports distinguish completed internal checks from open qualification.</p><h4>Newly integrated product work</h4><p>Named sketch parameters and retained construction steps support later edits and project persistence. The latest repairs address applied object movement, clockwise contour handling, explicit canvas operations, setup diagnostics and exact resource budget entry. Setup planning recognises supported straight geometries and a bounded single width transition.</p><h4>Previously calculated cases</h4><p>The open microstrip setup report records two independent excitations, 12 valid complex S entries at three frequencies, native fields, saved views and a checked Touchstone file. Its independent reconstruction checks existing raw records. The earlier closed eight port case has its own 192 entry result and scope. These counts are not accuracy metrics.</p><h4>What the latest checkpoint did not establish</h4><p>No new electromagnetic trajectories or physical mode solutions were run for the latest integration. Planning a width transition does not qualify its RF response. A new complete desktop workflow demonstration and its new two excitation completion remain open. Earlier failed patch attempts retain their failed status.</p><h4>How this review was performed</h4><p>The review read the current Project Master, the integration and independent review reports, selected source declarations, material scope and prior numerical records. It did not build or run the Windows application, repeat solver tests or audit every source file. Private source code, reports, local paths and raw project data are not distributed with this website.</p><h4>Image dates remain separate</h4><p>The public field and Smith captures were selected on 13 September. They have no independently supplied executable build identity and are not attributed to the latest source revision. The numerical diagnostic plots and analytical reference records retain their own original provenance.</p><p><a href="evidence/development-scope.md" target="_blank" rel="noopener noreferrer">Read the dated scope summary ↗</a></p>`,'CURRENT DEVELOPMENT');}
function showAnalytic(){openInfo('Saved analytical reference values',`<span class="tag">SI Kernel v0.3 · Historical reference dataset</span><p>The three selectable records were copied unchanged from <code>differentialPairSpacingSweep</code>. The display rounds the values; the local JSON file retains their full original stored precision.</p><p>Geometry: edge coupled microstrip with εᵣ = 4.1, substrate height 0.5 mm, trace width 0.5 mm and idealised thickness 0 mm. Available spacings: 0.10 mm, 0.25 mm and 0.50 mm.</p><p>The recorded relationships are Z diff = 2 · Z odd and Z common = Z even / 2. Selecting a record does not interpolate further values or launch a calculation.</p><p>The source describes the records as internally audited analytical references. That description is attributed to the source; it is not a new independent audit. These are neither 3D field simulations nor experimental or externally validated results.</p><p><a href="evidence/analytical-spacing.json" download>Download the original values as JSON ↓</a><br><a href="${sourceBase}data/dad_signal_integrity_v0_3_examples.json" target="_blank" rel="noopener noreferrer">Complete public source dataset ↗</a><br><a href="${sourceBase}docs/live_engineering_examples_provenance.md" target="_blank" rel="noopener noreferrer">Original data provenance ↗</a></p>`,'DATA & INTERPRETATION');}
// All dynamic copy and labels are English. Data values remain unchanged.
document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;if(b.dataset.tab)renderResult(b.dataset.tab);if(b.dataset.view)renderView(b.dataset.view);if(b.dataset.evidence)renderEvidence(b.dataset.evidence);if(b.dataset.openImage)openImage(b.dataset.openImage);if(b.dataset.source)showSource(b.dataset.source);if(b.dataset.verify)verifyFile(b.dataset.verify);if(b.hasAttribute('data-spacing'))updateSpacing(Number(b.dataset.spacing));if(b.hasAttribute('data-close'))closeModal(b.closest('dialog'));if(b.dataset.dialog)({register:showRegister,scope:showScope,development:showDevelopment,analytic:showAnalytic}[b.dataset.dialog])();});
$('#expand-result').addEventListener('click',()=>openImage(currentAsset==='compare'?'hy-contours':currentAsset));$('#result-source').addEventListener('click',()=>showSource(currentAsset==='compare'?'hy-contours':currentAsset));$('#zoom').addEventListener('input',updateZoom);$('#zoom-reset').addEventListener('click',()=>{$('#zoom').value=100;updateZoom();$('#zoom-viewport').scrollTo(0,0);});
document.addEventListener('input',e=>{if(e.target.id==='source-search')$('#register-list').innerHTML=registerHTML(e.target.value);});
$$('[role=tablist]').forEach(list=>list.addEventListener('keydown',e=>{if(!e.target.matches('[role=tab]'))return;const tabs=[...list.querySelectorAll('[role=tab]')],i=tabs.indexOf(e.target);let next=i;if(['ArrowRight','ArrowDown'].includes(e.key))next=(i+1)%tabs.length;else if(['ArrowLeft','ArrowUp'].includes(e.key))next=(i-1+tabs.length)%tabs.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=tabs.length-1;else return;e.preventDefault();tabs[next].click();tabs[next].focus();}));
renderResult('field');renderEvidence('pulse');
